# name: Angular CD
# on:
#   push:
#     tags:
#       - 'v*'

#     branches:
#       - main
#       - staging
#       - develop

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Deploy to Production
#       run: bash deploy.sh production
