name: Deployment

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "Image tag"
        default: 0.0.0-main
        type: string
      namespace:
        description: "Namespace"
        default: staging
        required: true
        type: string
      undeploy:
        description: "Undeploy namespace"
        default: false
        type: boolean

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client
      - name: Configure kubectl
        run: |
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
      - name: Deploy to ${{ inputs.namespace }}
        if: ${{ !input.undeploy }}
        run: |
          helm upgrade pocket-mall --install --set image.tag=${{ inputs.imageTag }} --create-namespace ${{ inputs.namespace }} -n ${{ inputs.namespace }} ./helm
      - name: Undeploy ${{ inputs.namespace }}
        if: ${{ input.undeploy }}
        run: |
          helm uninstall ${{ inputs.namespace }}
          kubectl delete namespace ${{ inputs.namespace }}